# MLP with Keras and Scikit-learn 

### Keras

    Keras is a high-level neural networks library, written in Python and capable of running on top of either TensorFlow, CNTK or Theano. Allows for easy and fast prototyping.

# Problem Statement

This dataset is originally from the National Institute of Diabetes and Digestive and Kidney Diseases. The objective of the dataset is to diagnostically predict whether or not a patient has diabetes, based on certain diagnostic measurements included in the dataset. Several constraints were placed on the selection of these instances from a larger database. In particular, all patients here are females at least 21 years old of Pima Indian heritage.

Can you build a machine learning model to accurately predict whether or not the patients in the dataset have diabetes or not?

#### Load Data

In [11]:
import numpy

Fix random seed for reproducibility

In [12]:
numpy.random.seed(123)

Check the current working directory 

In [13]:
import os

PATH = os.getcwd()

PATH

'/Users/iampraveenvemula/Desktop/kla/ann/today'

Set directory to the place where csv file exist

In [14]:
os.chdir(PATH)

Load pima indians dataset

In [15]:
data = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")

Print the data

In [16]:
print(data)

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]


Print the shape of the data

In [17]:
print (data.shape)

(768, 9)


Seperate independent variables(X) and target variable(y)

In [18]:
X = data[:,0:8]
y = data[:,8]

Using sklearn package, split X and y into training and testing sets

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=4)

Print the shapes of the new X objects

In [20]:
print(X_train.shape)

print(X_test.shape)

(576, 8)
(192, 8)


Print the shapes of the new y objects

In [21]:
print(y_train.shape)

print(y_test.shape)

(576,)
(192,)


#### Define Model

1. Models in Keras are defined as a sequence of layers.

2. First sequential model is created and layers are added one at a time. 

__Note__:The best network structure is found through a process of trial and error experimentation.

Now we will build a fully-connected network structure with two layers.

    The first layer has 12 neurons and expects 8 input variables. 
    Finally the output layer has 1 neuron to predict the class

In [22]:
import tensorflow as tf


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
model = Sequential()

The Sequential model is a linear stack of layers. 
Sequential model is created by passing a list of layer instances to the constructor or by simply add layers via the .add() method:

In [24]:
model.add(Dense(12, input_dim=8, activation='tanh', kernel_initializer='uniform'))
model.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))

Dense implements the operation: output = activation(dot(input, kernel) + bias) where activation is the element-wise activation function passed as the activation argument, kernel is a weights matrix created by the layer, and bias is a bias vector created by the layer (only applicable if use_bias is True).


Note: If the input to the layer has a rank greater than 2, then it is flattened prior to the initial dot product with kernel.

Fully connected layers are defined using the Dense class. 

We specify 
    1. The number of neurons in the layer as the first argument
    2. The model needs to know what input shape it should expect. For this reason, the first layer in a Sequential model (and only the first, because following layers can do automatic shape inference) needs to receive information about its input shape. One way is using input_dim argument. 
    3. The activation function using the activation argument. ‘tanh‘ activation function is used in first layer and the sigmoid activiation function in the output layer. 
    4. Initializations define the way to set the initial random weights of Keras layers. We initialize the network weights to a small random number generated from a uniform distribution (‘uniform‘).
    

#### Compile Model

Before training a model, you need to configure the learning process, which is done via the compile method. It receives three arguments:

    an optimizer     : This could be the string identifier of an existing optimizer (such as rmsprop or adagrad or sgd), or an instance of the Optimizer class.
    
    a loss function  : This is the objective that the model will try to minimize. It can be the string identifier of an existing loss function (such as categorical_crossentropy or mse), or it can be an objective function.
    
    a list of metrics: For any classification problem you will want to set this to metrics=['accuracy']. A metric could be the string identifier of an existing metric or a custom metric function.

In [45]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

#### Training

Keras models are trained on Numpy arrays of input data and labels. For training a model, you will typically use the fit function.

Fit the model

In [46]:
model.fit(X_train, y_train, epochs=50, batch_size=32)

Train on 576 samples
Epoch 1/50
576/576 [==============================] - 1s 1ms/sample - loss: 0.5897 - accuracy: 0.6649
Epoch 2/50
576/576 [==============================] - 0s 146us/sample - loss: 0.5784 - accuracy: 0.6719
Epoch 3/50
576/576 [==============================] - 0s 99us/sample - loss: 0.5842 - accuracy: 0.6840
Epoch 4/50
576/576 [==============================] - 0s 81us/sample - loss: 0.5825 - accuracy: 0.6649
Epoch 5/50
576/576 [==============================] - 0s 129us/sample - loss: 0.5837 - accuracy: 0.6632
Epoch 6/50
576/576 [==============================] - 0s 107us/sample - loss: 0.5801 - accuracy: 0.6736
Epoch 7/50
576/576 [==============================] - 0s 82us/sample - loss: 0.5794 - accuracy: 0.6753
Epoch 8/50
576/576 [==============================] - 0s 107us/sample - loss: 0.5846 - accuracy: 0.6562
Epoch 9/50
576/576 [==============================] - 0s 115us/sample - loss: 0.5759 - accuracy: 0.6771
Epoch 10/50
576/576 [===========================

    x         : input data, as a Numpy array or list of Numpy arrays (if the model has multiple inputs).
    y         : labels, as a Numpy array.
    batch_size: integer. Number of samples per gradient update.
    epochs  : integer, the number of epochs to train the model.

#### Evaluate Model

In this case we trained neural network on the entire dataset and evaluating its on the same dataset.

In [47]:
scores = model.evaluate(X_train, y_train, verbose=2)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

576/1 - 0s - loss: 0.5819 - accuracy: 0.6858
accuracy: 68.58%


#### Predictions

Predict using model.predict().  
We are using a sigmoid activation function in the output layer, so the predictions will be in the range between 0 and 1.

In [48]:
predictions = model.predict(X_train)
print(predictions)

[[0.3185854 ]
 [0.33325595]
 [0.4247436 ]
 [0.43414596]
 [0.26239604]
 [0.43414596]
 [0.43415147]
 [0.26994842]
 [0.23677936]
 [0.23907205]
 [0.06123254]
 [0.09893322]
 [0.17534068]
 [0.1150158 ]
 [0.43414596]
 [0.43414596]
 [0.59745014]
 [0.17666921]
 [0.17751509]
 [0.0978654 ]
 [0.43414596]
 [0.09864441]
 [0.09785721]
 [0.29327458]
 [0.09791175]
 [0.14907527]
 [0.09785417]
 [0.36396557]
 [0.21124044]
 [0.5241606 ]
 [0.4404304 ]
 [0.31329882]
 [0.09785917]
 [0.38102448]
 [0.59752315]
 [0.43411338]
 [0.10834095]
 [0.17925638]
 [0.6682084 ]
 [0.11222836]
 [0.6918935 ]
 [0.09798586]
 [0.4341458 ]
 [0.17666563]
 [0.5256457 ]
 [0.18283415]
 [0.08099049]
 [0.43414596]
 [0.43410566]
 [0.43414596]
 [0.43414596]
 [0.17795238]
 [0.30529848]
 [0.25775272]
 [0.29420334]
 [0.21377024]
 [0.43414262]
 [0.17682621]
 [0.09346724]
 [0.5382214 ]
 [0.3612798 ]
 [0.10204491]
 [0.36330026]
 [0.16031379]
 [0.09789887]
 [0.53839004]
 [0.18003032]
 [0.43187985]
 [0.35137647]
 [0.43414593]
 [0.36417502]
 [0.43

In [49]:
model.predict_classes(X_train)[0:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int32)

In [50]:
y_pred_class = model.predict_classes(X_test)
print(y_pred_class)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


Calculate accuracy of class predictions

In [51]:
from sklearn import metrics

from sklearn.metrics import classification_report

metrics.accuracy_score(y_test, y_pred_class)

0.6927083333333334

Print the confusion matrix

In [52]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[113,  13],
       [ 46,  20]])

In [53]:
print(classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

         0.0       0.71      0.90      0.79       126
         1.0       0.61      0.30      0.40        66

    accuracy                           0.69       192
   macro avg       0.66      0.60      0.60       192
weighted avg       0.67      0.69      0.66       192



In [56]:
# Can you tune hyperparameters to improve the recall & precision score?

Reference:

    https://keras.io/